package cn.rongcapital.mkt.dataauth.po;

import java.util.Date;

public class DataAuth {

    private Long daId;
    private String tableName;
    private Long resourceId;
    private Long orgId;
    private Boolean firsthand;
    private String shareType;
    private Boolean writeable;
    private Long fromOrgId;
    private Long fromResourceId;
    private Boolean shared;
    private String shareId;
    private Date daCreateTime;
    private Date daUpdateTime;

    
    
    /**
     * 
     */
    public DataAuth() {
        super();
    }

    /**
     * @param tableName
     * @param resourceId
     */
    public DataAuth(String tableName, Long resourceId) {
        super();
        this.tableName = tableName;
        this.resourceId = resourceId;
    }

    public Long getDaId() {
        return daId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.da_id
     * @param daId  the value for data_auth.da_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setDaId(Long daId) {
        this.daId = daId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.table_name
     * @return  the value of data_auth.table_name
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.table_name
     * @param tableName  the value for data_auth.table_name
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.resource_id
     * @return  the value of data_auth.resource_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.resource_id
     * @param resourceId  the value for data_auth.resource_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.org_id
     * @return  the value of data_auth.org_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.org_id
     * @param orgId  the value for data_auth.org_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.firsthand
     * @return  the value of data_auth.firsthand
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public Boolean getFirsthand() {
        return firsthand;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.firsthand
     * @param firsthand  the value for data_auth.firsthand
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setFirsthand(Boolean firsthand) {
        this.firsthand = firsthand;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.share_type
     * @return  the value of data_auth.share_type
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public String getShareType() {
        return shareType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.share_type
     * @param shareType  the value for data_auth.share_type
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setShareType(String shareType) {
        this.shareType = shareType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.writeable
     * @return  the value of data_auth.writeable
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public Boolean getWriteable() {
        return writeable;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.writeable
     * @param writeable  the value for data_auth.writeable
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setWriteable(Boolean writeable) {
        this.writeable = writeable;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.from_org_id
     * @return  the value of data_auth.from_org_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public Long getFromOrgId() {
        return fromOrgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.from_org_id
     * @param fromOrgId  the value for data_auth.from_org_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setFromOrgId(Long fromOrgId) {
        this.fromOrgId = fromOrgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.from_resource_id
     * @return  the value of data_auth.from_resource_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public Long getFromResourceId() {
        return fromResourceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.from_resource_id
     * @param fromResourceId  the value for data_auth.from_resource_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setFromResourceId(Long fromResourceId) {
        this.fromResourceId = fromResourceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.shared
     * @return  the value of data_auth.shared
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public Boolean getShared() {
        return shared;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.shared
     * @param shared  the value for data_auth.shared
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setShared(Boolean shared) {
        this.shared = shared;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.share_id
     * @return  the value of data_auth.share_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.share_id
     * @param shareId  the value for data_auth.share_id
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setShareId(String shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.daCreateTime
     * @return  the value of data_auth.create_time
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public Date getDaCreateTime() {
        return daCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.create_time
     * @param daCreateTime  the value for data_auth.create_time
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setDaCreateTime(Date daCreateTime) {
        this.daCreateTime = daCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column data_auth.update_time
     * @return  the value of data_auth.update_time
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public Date getDaUpdateTime() {
        return daUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column data_auth.update_time
     * @param updateTime  the value for data_auth.update_time
     * @mbg.generated  Thu Jan 26 22:08:15 CST 2017
     */
    public void setDaUpdateTime(Date updateTime) {
        this.daUpdateTime = updateTime;
    }
}